web:
  image: elaworkshop/haloword-server:1.0
  ports:
    - "6603:8000"
  volumes:
    - ~/docker/haloword-server/settings.py:/app/settings.py
  links:
    - redis
redis:
  image: redis:3.0.7-alpine
  volumes:
    - ~/docker/haloword-server/redis.conf:/usr/local/etc/redis/redis.conf
    - ~/docker/haloword-server:/data
