web:
  image: elaworkshop/haloword-server:1.0
  ports:
    - "6603:8000"
  volumes:
    - ./settings.py:/app/settings.py
  links:
    - redis
redis:
  image: redis:3.0.7-alpine
  volumes:
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    - ./redis:/data
